python preprocessing_amass.py --dataset_name=ACCAD --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > ACCAD
# BMLmovi: Subject 49-19 error -> erased.
python preprocessing_amass.py --dataset_name=BMLmovi --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > BMLmovi
python preprocessing_amass.py --dataset_name=BMLrub --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > BMLrub
python preprocessing_amass.py --dataset_name=CMU --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > CMU
python preprocessing_amass.py --dataset_name=CNRS --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > CNRS
python preprocessing_amass.py --dataset_name=DFaust --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > DFaust
python preprocessing_amass.py --dataset_name=EKUT --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > EKUT
python preprocessing_amass.py --dataset_name=Eyes_Japan_Dataset --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > Eyes_Japan_Dataset
python preprocessing_amass.py --dataset_name=GRAB --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > GRAB
python preprocessing_amass.py --dataset_name=HDM05 --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > HDM05
python preprocessing_amass.py --dataset_name=HumanEva --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > HumanEva
python preprocessing_amass.py --dataset_name=KIT --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > KIT
python preprocessing_amass.py --dataset_name=MoSh --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > MoSh
python preprocessing_amass.py --dataset_name=PosePrior --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > PosePrior
python preprocessing_amass.py --dataset_name=SFU --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > SFU
python preprocessing_amass.py --dataset_name=SOMA --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > SOMA
python preprocessing_amass.py --dataset_name=SSM --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > SSM
python preprocessing_amass.py --dataset_name=TCDHands --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > TCDHands
python preprocessing_amass.py --dataset_name=TotalCapture --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > TotalCapture
python preprocessing_amass.py --dataset_name=Transitions --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > Transitions
python preprocessing_amass.py --dataset_name=WEIZMANN --amass_root=datasets/AMASS_smplx_neutral --save_root=datasets/AMASS_smplx_preprocessed > WEIZMANN
